export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  DASHBOARD: '/dashboard',
  NOTIFICATIONS: '/notifications',
  MESSAGES: '/messages',
  PROFILE: '/profile',
  JOBS: '/jobs',
  SAVED: '/saved',
  PREMIUM: '/premium',
  WALLET: '/wallet',
  RECOMMENDATIONS: '/discover',
  GROWTH: '/growth',
} as const;
